apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:40dxDZZ88K8FD82yEXdHO5Q/4MK/JNUzIXurzBGnph0aKeDwhlcdgkuVQL7fswhvyTcpADrNt23E6FPE3jl4MhgZ7OdQuDZWZbPapi9EDs+Tg5zVJyh4cbNCwclBkhlmtLUUuQN+U/6YdEGzs8p1f/jhkl65rt3YMHrvaSquBF7Hpay1QXiU3XZ3L2MXngzYQyGgHSfWIXePHgTHS2RoU+6Ip2RwzR201I7ZhJyBg/MgDzcj0Tpz1tELB7VogSfdN154RJ1anz/gJQVn4/EXKDkrdlqn4N771LzhimH3QFySqYLUONAG3b+muqoryCEwooyiUqy1X1LpImiUGbAIm8c1EHrrAAIDpuinzbKq27G9tRi9dL/Wj1JH+G/jAR0S,iv:WJdg81LQs+GMRAVxvSmVJ1m9KszIXRHz8BBvFdy7k2Q=,tag:pVDR32k3vALe3D073FlryA==,type:str]
    identity.pub: ENC[AES256_GCM,data:1wbUn0Mimq3O7504kzqJMTsSkJ/Ulr1Ng/u/1n17CZ5b1q2G/VLdzz0kEjYCPYu+41ycDdd68pUoypgaz0Cp0Jfy2cQn4vdWhuRhVBtQGc6CgtUxz41f/W4PSddyoOvK+dArAIX6o85q86JqJvzs7fiHgrPJnl9AEuehzufNT22f/UOZ/W2xTNGzihskbWn2JllEmjMo3OQibvXWdAvUM8PKyZd6cijQtJFseOVT6QAbyjEOaqTxMn9b05HiZXhIEB+Gbp+IJhU8Lisz/w==,iv:k5658FIlZH9yB7CFYVod11IXivmRO7thmHrxy0WhvfI=,tag:cQ0SpJhkuoPWABOe0olHhQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:FgsbjPxkP6oYPUljHBM7IjIWDutqtbeweVdXO++u2qubw+aUTKK6pfLU1w3IdnApO6qbYMQPFw3VdlDX5dmX/jWCvRlg94U4nYJlaajoH4ComHKkZ5bQyybx/jHfzRk3/4vj5M7dKQRi6Eb5qUN6/2QVpge9ILanvkelbPpW7sZQTpoasJ9DRpELcWAvExTXPWjtauZ8R/33q/nq7R9zXftGEyjwLnWFBUe9,iv:QjReOwyVLduUeizPFkOapI3LDhFqLnLdxVPSC7eljXQ=,tag:Kq4YQwUewNORe4sMRQpoTQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j6qv68r7parwcdr2m2pnjlql2thz7una2jca45trwmmm47kvsuqq4ad7ts
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyS3cybCthMFlNakZuVDVJ
            Y3IxSmROM01OUGNWamhDTEF6T2dqbG4vRVJzCm5nSFVXUDlNVEZyeVZYV3I1OFhm
            N1FrQ01ORjdTbHFIa25lOEphRGI5NHcKLS0tIDBSN20rMkQvc0FyZ1JjVklOREhN
            THltK1d2ZENWOXdRVGxCWnYxajRpRUkKrCKEedIdFSS1lwS2wid9jYtHjQEqrztG
            G7ABHZyeWlpoOwWoMsTmGTVkayFQj/H0pvm/n/3wdaWQSLm3XupezA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-14T22:53:15Z"
    mac: ENC[AES256_GCM,data:05sK7g9kZy1aendmrpAviztE98xiQjKq+dDKZbzs0iNfuw4gkTywPDJpS28jhhzCDuwPsvnFpdqSogoAst/oxKBl3OiczVPv8YazH54Sfgqwikv+OdpvCDp8618m2WcOeXtea0QVJsEsOjNOL4HK8LshLKXx8E0t2syi9PMfrNg=,iv:agBXY8jQto6KHhNsz7r6YjOiuaF5HeCv5WG1kEfZIrg=,tag:Nh86yYnRjp4ZiK0Mw4IPjg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
