apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:LBzdoPw0kAtkS/ZAyi7kc13tg0vhXRHXVSvW4huRfxhUNNNYGMRdFTZKdIH3R1rUxjFqkJcJTBUInDKBB80KTzb9Nl9d+9g2Ebef6x5eYAFRN/mSrMPijxCPLIZW5cBZLRfmkInP9uYQs+nHCm3wnBKtq4UCcEc7jrvOa8kBCVmwLYlLJoC8EbwhfLYu3pgGmkJitL0tFGBbFSnjvKVhjdiRNu99gw1/25yf7QwS3YKJrJaj1k1H6eEyBkFz/MhkJz172QEdHyTpZXZ1psC26C+OkLhmlcpUViiJP73rhP239zUHsLTJHgPbuk5SqCVdqpZELK+2C1ZOvxyuphwcXwqTFAAMQ5g4W4TEolq6s+6KCoHmBflo0OByE15nKOhN,iv:Ah1CyA/o7iCKHRaORUHPMNN/Op+iJhtRL0JVNVMIXeA=,tag:2b9S0n3m2LCDbR/2mQDVEw==,type:str]
    identity.pub: ENC[AES256_GCM,data:sf0yFFlbZ8zncOU/cPcF09kCjNy6fdXMnbYJpXzCUKptySL6RTv3OCoFMcY5bqA3glinvKs/UC1VHZVqvwXcfxkQmF3OSjv6n+Ux5M1Nm/tFnleqOteigVhRYUb/t2AbhrkzLzzoIMCVYXEH4Un5P9OGtqg4PfNhMxo/xOXK1/1L+XZYKKYBi1hG6RPH4IwyVu72DTRA+BibAn3Z0SBUEmf9bTyGru2ZOk9uquq2D+SsmsH09yOECN8x8FiPf2zw8j8SqJazA6s6VBsg6A==,iv:gTuCoWiuEVAZriBKDQRd8PbxAyl0xSnnH6kop18hli0=,tag:F2/ACqUar7KXu7Z9x4XsmQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:e5ntFnBS6RAeslx4P0Gk78LxjL7sKGbpFb15oe4oUocepmZKGkCahL4YCYTNlU5R6LxNtIVO3uvCJ8AQWz7R3PXxUr0/GiS/o2+watXeL2cvNKkHKK5F1gftb4RfeDMTyoxMmex6XVBHCDNz6oYJN+6tqBHJH+u6xjCjeY2Puq+wSGIKp99mAoFqGQDxFm877o0FykhMVtPqGdWK0dz8nNWTekvMJvKTf9NU,iv:u7oG4dHIwaI8ymw3Gvi3+kEkAgi/VIARxJ9Q7BlCBq4=,tag:YDqyC3W2ptk/h8zTMPYyJQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j6qv68r7parwcdr2m2pnjlql2thz7una2jca45trwmmm47kvsuqq4ad7ts
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmQWQ4VGdyVE02bUgyeWQv
            SnlrRzZIdUx6eUc3cVRiZm0vSWsvUm83UldjCm5NZ1RycDBJOE5EYStCaWRHaG53
            QW1SSWoxNCtDVFJCK0R3Q293VzgxRzAKLS0tIDVZSmN6VW1HNFp4M3F4Zk1RWk8x
            N2dWYnBwdFlIVllqOW5QM3V3clgyNWMKpVziz4JSUPBDRKipFgerX9EGFKbBLIt4
            b4Xvv7lv9JWNkpydDTIKmBCPdDQAx/RWz/qKno7txPja3YL1F+4tJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-16T03:36:25Z"
    mac: ENC[AES256_GCM,data:GY/ukj3shSi/YqBOXqjFTpXJSymKPpyxchxcLES/Q7rf1yAR6tSzQOIo5+n7Gp1ojl53PQqonBll2huMTQ5SlD/hTy1UiHJ0QOuBwxhi8sH+JKDfyojjxqX/zIVeWnegN0ZmPtFZM1qHOzfNhdGsjpAIgyAjquDHctDCxcUVDPQ=,iv:VCjdC3tRg+71jbBp0N5nXCybTWT7oThIaKAgwhv4CmU=,tag:VKS/MstEK9c+j7v7CYr7Hw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
