apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:wGm15rde1Kov42WG5dtu/5J/FEzK5R8/ZiQ3k4YjYmen5v1DE9pE1vPLepibzCD6FRTZHNFMxjCd3veMkZtiHIYZTx7UDGPSBokc1lBQiBJEu6+RmL2arAVpA3BJ5MLxE6XKMfksd5Bj7Bw98KQoiGmfMIOTpSamXN5zS17s5wf1/jIXtLUYNRhGuCaFKevK0gyKEIBxHlGsf3LMeRQAjOtDjW46q2HYZrw7OjpzQpOPtQeHM9P9KM6W5Bgq0eA0M10NiCZ+LCXlDgu/QNxOfm9kt7ptP4HjCXkgRamilTD/CZuKfuQ6aXfzQwvDW4rMHxU/sxpWuqUGyqEjS7XZl14P90hzR5UheIsw1p/oUctTbq5wyVsCkeoQeDt5QvJK,iv:0m+1OzjFrmnigkicFomNwdRzYFgQkRDGbSNRAxDx4uM=,tag:Y6dSHTMpF5TegPqojQbLTg==,type:str]
    identity.pub: ENC[AES256_GCM,data:jlCIzV/lHdfNG2bXVTxyPt+Mcr1IIXmCfUaYYczytWQAo1Cg2OJanyaC9J+VAN6M6pY5g5/dMBqsNeABsRcAmYCiXRKJH9DzS6TuEeWltKV/eUMfLPmkAkGkllQaDCVPSBt8NfyDCyl029KjiF2JDfWcz/80vV+r6qI06LpHuLaCYF0fmIobf78fPLUXeD4yYtp8UktHH1moSMUx0wCRX4u10C0fYDPBBfNUcYrgGIviC9fmHpDUABF9SKkglmMRuxrAG6mLRl7daLqQ6w==,iv:yAKHRS+6tAUHCBSLKeErdLbgzVQzfgCP8SGT9PYngQ4=,tag:u+HlEku4MDHQhv2XY1okOA==,type:str]
    known_hosts: ENC[AES256_GCM,data:9nob2+G5fJnYIgOT49XRg9e3cOJHkctbz1E+k3T4Lcx+CgZINw41dFrxnNaODiEezGBaU3SmgFPLmikjrr8pnvc3Egh6NfdvyS3xgr0skHM0lGxPxCrTt3O4N+RadoKmaZC3tHZbtlthMFGSq/62BeBUNEHrbZaLXUIAeHDIJzMB66RbwlUjrD3dAwUMWFCZc5wYdnoqTF1GLDQBUB4eysGbGAi0Hh93rco6,iv:XN3b0c1ccf2i3rxajkGVshjJAGSumdCaiRokZeRln0k=,tag:wUHRkJRc6iqMhXWtwDwDFQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j6qv68r7parwcdr2m2pnjlql2thz7una2jca45trwmmm47kvsuqq4ad7ts
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVRUIxazkxTHBmLzRFZFV5
            WC92T2ZPbWN6N2dBRVpkQjlhalU3VWJPZ1RVCnk4Rys5dEwwNkpLUjdVb1E5b2s5
            Y0Y2dkRGOU1TSUFrc1JkNk9zODVuVVUKLS0tIG1kbllPaW82Y2F0YlROV1Zra20w
            S1RIb0pDc0RoQ3FWZExnVXVBVmVZeTAKAoHGcIP4HVc2maFKzuKUKUchmxcKAlDk
            LCkYDjLFSrfzvkiFfFmshBpTIpHBwB5E47B4Pxv0bH9Zjk+cywGA3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-15T01:04:57Z"
    mac: ENC[AES256_GCM,data:mrQF8BQfXr34YyCh/D79T2p4QijTfDAQ3DTX2UZa2dpSY9ZX976Myd9oILihLY1AYlJ/CrMH/9rtM32aWPlyLc5d/D+GbdKmc//LVyJOeij1211TH8fDFfXJg58S25zU96xGs7fdQ7UHAHF2zfD3NKta2UpNAycVWSIIB0XVml8=,iv:8//Aj0wy8OrkT4og8ioHZue0N4VzHnkQJlykmHS+/2g=,tag:S4R+tvP8cT8AueJP7iU6nQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
